name: mobile_pssi
description: A Flutter project for PSSI company.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.3+30

environment:
  sdk: ">=2.16.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  any_link_preview: ^2.0.9
  avatars: ^3.0.2
  bottom_inset_observer: ^3.1.0
  cached_network_image: ^3.2.0
  card_swiper:
    git:
      url: https://github.com/lazyfatcat/card_swiper
      ref: master
  crypto: ^3.0.2
  cupertino_icons: ^1.0.4
  currency_text_input_formatter: ^2.1.7
  dio: ^4.0.6
  dotted_border: ^2.0.0+2
  dropdown_search: ^5.0.3
  equatable: ^2.0.5
  fancy_password_field: ^1.0.4
  file_picker: ^5.2.0+1
  filesystem_picker: ^3.1.0
  fimber: ^0.6.6
  firebase_analytics: ^9.3.8
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  firebase_crashlytics: ^2.8.13
  firebase_messaging: ^13.1.0
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_facebook_auth: ^4.4.0+1
  flutter_inappwebview: ^5.4.4+3
  flutter_keyboard_visibility: ^5.3.0
  flutter_linkify: ^5.0.2
  # flutter_local_notifications: ^12.0.0
  awesome_notifications: ^0.7.0-beta.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10+3
  flutter_radar_chart: ^0.2.1
  flutter_rating_bar: ^4.0.0
  flutter_screenutil: ^5.5.3+2
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.1+1
  flutter_time_range: ^0.0.3
  flutter_widget_from_html: ^0.8.5
  font_awesome_flutter: ^10.1.0
  form_validator: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  grouped_list: ^5.1.2
  html2md: ^1.2.6
  html_editor_enhanced:
    git:
      url: https://github.com/ksilz/html-editor-enhanced
  http: ^0.13.4
  image_picker: ^0.8.6
  in_app_purchase: ^3.0.7
  internet_file: ^1.1.0
  intl: ^0.17.0
  markdown: ^6.0.0
  midtrans_sdk:
    git:
      url: https://github.com/rymesaint/midtrans_sdk.git
  mobile_scanner: ^3.0.0-beta.1
  multi_select_flutter:
    git:
      url: https://github.com/kabagouda/multi_select_flutter.git
      ref: patch-1
  octo_image: ^1.0.2
  package_info_plus: ^1.4.3+1
  path: ^1.8.0
  path_provider: ^2.0.9
  pdfx: ^2.2.0
  permission_handler: ^10.1.0
  pin_input_text_field: ^4.1.1
  pod_player: ^0.1.0
  progress_stepper: ^1.0.0
  pull_to_refresh:
    git:
      url: https://github.com/miquelbeltran/flutter_pulltorefresh
      ref: master
  pusher_client:
    git:
      url: https://github.com/fabiancrx/pusher_client
  readmore: ^2.2.0
  screenshot: ^1.2.3
  share_plus: ^4.5.2
  sign_in_with_apple: ^4.1.0
  simple_gravatar: ^1.1.0
  slide_countdown: ^0.3.4
  slider_button:
    git:
      url: https://github.com/da-nish/Slider-Button
  thumbnailer:
    git:
      url: https://github.com/rymesaint/thumbnailer
      ref: master
  timeago_flutter: ^1.1.0
  timer_count_down: ^2.2.1
  timezone: ^0.9.0
  url_launcher: ^6.1.6
  velocity_x: ^3.5.1
  video_thumbnail: ^0.5.2
  video_url_validator: ^1.0.2

dependency_overrides:
  xml: ^6.0.1

dev_dependencies:
  flutter_flavorizr: ^2.1.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  get_test: ^4.0.1
  mockito: ^5.3.2
  mocktail: ^0.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

flavorizr:
  ide: vscode
  instructions:
    - assets:download
    - assets:extract
    - android:buildGradle
    - android:androidManifest
    # - flutter:app
    - flutter:flavors
    # - flutter:targets
    - ios:xxconfig
    - ios:buildTargets
    - ios:schema
    - ios:plist
    # - google:firebase
    - assets:clean
    - ide:config

  app:
    android:
      flavorDimensions: "flavor-type"
    ios: null

  flavors:
    dev:
      app:
        name: "Prima Academy Dev"

      android:
        applicationId: "com.kunci.mobile_pssi"
        customConfig:
          versionNameSuffix: "\"-dev\""
        resValues:
          facebook_app_id:
            type: string
            value: "1013525912595665"
          fb_login_protocol_scheme:
            type: string
            value: "fb1013525912595665"
          facebook_client_token:
            type: string
            value: "be2bf940b8f88a29cfd056a4a689f9ba"
          firebase_channel_id:
            type: string
            value: "prima_academy_id"

      ios:
        bundleId: "com.kunci.mobilePssi"
        buildSettings:
          DEVELOPMENT_TEAM: JPZB3FMV4L

    staging:
      app:
        name: "Prima Academy Staging"

      android:
        applicationId: "com.kunci.mobile_pssi"
        customConfig:
          versionNameSuffix: "\"-staging\""
        resValues:
          facebook_app_id:
            type: string
            value: "1013525912595665"
          fb_login_protocol_scheme:
            type: string
            value: "fb1013525912595665"
          facebook_client_token:
            type: string
            value: "be2bf940b8f88a29cfd056a4a689f9ba"
          firebase_channel_id:
            type: string
            value: "prima_academy_id"

      ios:
        bundleId: "com.kunci.mobilePssi"
        buildSettings:
          DEVELOPMENT_TEAM: JPZB3FMV4L

    prod:
      app:
        name: "Prima Academy"

      android:
        applicationId: "com.kunci.mobile_pssi"
        resValues:
          facebook_app_id:
            type: string
            value: "1013525912595665"
          fb_login_protocol_scheme:
            type: string
            value: "fb1013525912595665"
          facebook_client_token:
            type: string
            value: "be2bf940b8f88a29cfd056a4a689f9ba"
          firebase_channel_id:
            type: string
            value: "prima_academy_id"

      ios:
        bundleId: "com.kunci.mobilePssi"
        buildSettings:
          DEVELOPMENT_TEAM: JPZB3FMV4L
