-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgVJctptTVSCmERfd0
omH+xqfiGLkXIsjmLzEcyulKMRSgCgYIKoZIzj0DAQehRANCAAQtmGv2ytWAvVjZ
IF9gwTdI19KPaT1c8Ya/WIYPRcqxKwtTuI9MZcZgZpHjJhCh/qcHO555QEv+o//J
Qn6+bb8z
-----END PRIVATE KEY-----